"""Post-Incident Review (PIR) generation service."""

from datetime import datetime
from typing import Optional

from app.models import StoredIncident, AuditEvent


def generate_pir(incident: StoredIncident, audit_events: list[dict]) -> str:
    """
    Generate a Post-Incident Review markdown document.

    Template-based generation from incident data and audit trail.
    """
    # Format timestamps
    created = incident.created_at.strftime("%Y-%m-%d %H:%M UTC")
    updated = incident.updated_at.strftime("%Y-%m-%d %H:%M UTC")

    # Build timeline from audit events
    timeline_entries = []
    for event in sorted(audit_events, key=lambda x: x.get("timestamp", "")):
        ts = event.get("timestamp", "")
        if ts:
            try:
                dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
                ts_formatted = dt.strftime("%Y-%m-%d %H:%M UTC")
            except:
                ts_formatted = ts
        else:
            ts_formatted = "Unknown time"

        action = event.get("action", "Unknown action")
        status = event.get("status", "")
        details = event.get("details", {})

        entry = f"- **{ts_formatted}**: {action}"
        if status:
            entry += f" ({status})"
        if details and isinstance(details, dict):
            if "message" in details:
                entry += f" - {details['message']}"
        timeline_entries.append(entry)

    timeline_md = "\n".join(timeline_entries) if timeline_entries else "- No events recorded"

    # Build triage section
    triage_md = "Not triaged"
    actions_md = "- No actions defined"
    runbook_md = "No runbook assigned"

    if incident.triage:
        t = incident.triage
        triage_md = f"""- **Incident Type**: {t.incident_type.value}
- **Severity**: {t.severity.value}
- **Confidence**: {t.confidence:.0%}
- **Risk Score**: {t.risk_score:.0%}
- **Owner Team**: {t.owner_team}
- **Summary**: {t.short_summary}"""

        if t.first_actions:
            actions_md = "\n".join(f"- {action}" for action in t.first_actions)

        if t.primary_runbook:
            rb = t.primary_runbook
            runbook_md = f"**{rb.runbook_name}** (Fit: {rb.fit_score:.0%})"
            if rb.runbook_url:
                runbook_md += f"\n- URL: {rb.runbook_url}"
            if rb.steps:
                runbook_md += "\n- Steps:\n" + "\n".join(f"  - {s}" for s in rb.steps)

    # Build decision section
    decision_md = "No decision recorded"
    if incident.status.value in ["approved", "rejected", "overridden"]:
        decision_md = f"**{incident.status.value.upper()}**"
        if incident.decision_by:
            decision_md += f" by {incident.decision_by}"
        if incident.decision_at:
            decision_md += f" at {incident.decision_at.strftime('%Y-%m-%d %H:%M UTC')}"
        if incident.decision_note:
            decision_md += f"\n\n> {incident.decision_note}"
        if incident.original_severity and incident.triage:
            if incident.original_severity != incident.triage.severity:
                decision_md += f"\n\n*Severity changed from {incident.original_severity.value} to {incident.triage.severity.value}*"

    # Assemble full PIR document
    pir = f"""# Post-Incident Review: {incident.title}

**Incident ID**: {incident.id}
**Created**: {created}
**Last Updated**: {updated}
**Status**: {incident.status.value.upper()}

---

## 1. Summary

**Title**: {incident.title}

**Component**: {incident.component}
**Environment**: {incident.environment.value}
**Reporter**: {incident.reporter}

### Description

{incident.description}

---

## 2. AI Triage Results

{triage_md}

---

## 3. Recommended Actions

{actions_md}

---

## 4. Assigned Runbook

{runbook_md}

---

## 5. Decision

{decision_md}

---

## 6. Timeline

{timeline_md}

---

## 7. Root Cause Analysis

*To be completed by incident responders.*

- **Root Cause**:
- **Contributing Factors**:

---

## 8. Impact Assessment

*To be completed by incident responders.*

- **Users Affected**:
- **Duration**:
- **Services Impacted**:

---

## 9. Lessons Learned

*To be completed after incident resolution.*

- **What went well**:
- **What could be improved**:
- **Action items**:

---

## 10. Follow-up Actions

- [ ] Update runbook if needed
- [ ] Create tickets for improvements
- [ ] Schedule post-incident meeting
- [ ] Update monitoring/alerting

---

*Generated by Incident Autopilot at {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}*
"""

    return pir
